[project]
name = "check-uv"
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.12.*"
dependencies = [
    "scikit-learn",
    "sktime",
    "polars",
    "joblib",
    "psutil"
]
